#!/bin/sh
sxhkd &
feh --bg-fill ~/.bg
xrdb merge /home/lunarised/configs/PersonalConfig/.Xresources
bspc monitor -d I II III IV V VI VII VIII IX X
bspc config border_width	3
bspc config window_gap		12

bspc config split_ratio		0.5
bspc config borderless_monocle	true
bspc config
polybar -r mybar
nm-applet
